// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/03/02.

#ifndef PDK_UTILS_TRANSLATOR_PRIVATE_H
#define PDK_UTILS_TRANSLATOR_PRIVATE_H

namespace pdk {
namespace utils {

enum {
   P_EQ          = 0x01,
   P_LT          = 0x02,
   P_LEQ         = 0x03,
   P_BETWEEN     = 0x04,
   
   P_NOT         = 0x08,
   P_MOD_10      = 0x10,
   P_MOD_100     = 0x20,
   P_LEAD_1000   = 0x40,
   
   P_AND         = 0xFD,
   P_OR          = 0xFE,
   P_NEWRULE     = 0xFF,
   
   P_OP_MASK     = 0x07,
   
   P_NEQ         = P_NOT | P_EQ,
   P_GT          = P_NOT | P_LEQ,
   P_GEQ         = P_NOT | P_LT,
   P_NOT_BETWEEN = P_NOT | P_BETWEEN
};

} // utils
} // pdk

#endif // PDK_UTILS_TRANSLATOR_PRIVATE_H
