// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/01/18.

#include "gtest/gtest.h"

#include "pdk/stdext/preprocessor/Comparison.h"

TEST(ComparisonTest, testComparison)
{
   ASSERT_EQ(PDK_PP_EQUAL(2, 0), 0);
   ASSERT_EQ(PDK_PP_EQUAL(2, 2), 1);
   
   ASSERT_EQ(PDK_PP_NOT_EQUAL(2, 0), 1);
   ASSERT_EQ(PDK_PP_NOT_EQUAL(2, 2), 0);
   
   ASSERT_EQ(PDK_PP_LESS(2, 1), 0);
   ASSERT_EQ(PDK_PP_LESS(1, 2), 1);
   
   ASSERT_EQ(PDK_PP_LESS_EQUAL(2, 1), 0);
   ASSERT_EQ(PDK_PP_LESS_EQUAL(1, 2), 1);
   ASSERT_EQ(PDK_PP_LESS_EQUAL(2, 2), 1);
   
   ASSERT_EQ(PDK_PP_GREATER(2, 1), 1);
   ASSERT_EQ(PDK_PP_GREATER(2, 2), 0);
   
   ASSERT_EQ(PDK_PP_GREATER_EQUAL(1, 2), 0);
   ASSERT_EQ(PDK_PP_GREATER_EQUAL(2, 2), 1);
   ASSERT_EQ(PDK_PP_GREATER_EQUAL(3, 2), 1);
}
