// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/01/15.

// ****************************************************************************
// *                                                                          *
// *     (C) Copyright Paul Mensonides 2002-2011.                             *
// *     (C) Copyright Edward Diener 2011.                                    *
// *     Distributed under the Boost Software License, Version 1.0. (See      *
// *     accompanying file LICENSE_1_0.txt or copy at                         *
// *     http://www.boost.org/LICENSE_1_0.txt)                                *
// *                                                                          *
// ****************************************************************************
// 
// See http://www.boost.org for most recent version.

#ifndef PDK_STDEXT_PREPROCESSOR_SEQ_INTERNAL_SPLIT_H
#define PDK_STDEXT_PREPROCESSOR_SEQ_INTERNAL_SPLIT_H

#include "pdk/stdext/preprocessor/config/Config.h"

// PDK_PP_SEQ_SPLIT
# define PDK_PP_SEQ_SPLIT(n, seq) PDK_PP_SEQ_SPLIT_D(n, seq)
#
# if ~PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_MWCC()
#    define PDK_PP_SEQ_SPLIT_D(n, seq) (PDK_PP_SEQ_SPLIT_ ## n seq)
# else
#    define PDK_PP_SEQ_SPLIT_D(n, seq) (PDK_PP_SEQ_SPLIT_ ## n ## seq)
# endif
#
# define PDK_PP_SEQ_SPLIT_1(x) (x),
# define PDK_PP_SEQ_SPLIT_2(x) (x) PDK_PP_SEQ_SPLIT_1
# define PDK_PP_SEQ_SPLIT_3(x) (x) PDK_PP_SEQ_SPLIT_2
# define PDK_PP_SEQ_SPLIT_4(x) (x) PDK_PP_SEQ_SPLIT_3
# define PDK_PP_SEQ_SPLIT_5(x) (x) PDK_PP_SEQ_SPLIT_4
# define PDK_PP_SEQ_SPLIT_6(x) (x) PDK_PP_SEQ_SPLIT_5
# define PDK_PP_SEQ_SPLIT_7(x) (x) PDK_PP_SEQ_SPLIT_6
# define PDK_PP_SEQ_SPLIT_8(x) (x) PDK_PP_SEQ_SPLIT_7
# define PDK_PP_SEQ_SPLIT_9(x) (x) PDK_PP_SEQ_SPLIT_8
# define PDK_PP_SEQ_SPLIT_10(x) (x) PDK_PP_SEQ_SPLIT_9
# define PDK_PP_SEQ_SPLIT_11(x) (x) PDK_PP_SEQ_SPLIT_10
# define PDK_PP_SEQ_SPLIT_12(x) (x) PDK_PP_SEQ_SPLIT_11
# define PDK_PP_SEQ_SPLIT_13(x) (x) PDK_PP_SEQ_SPLIT_12
# define PDK_PP_SEQ_SPLIT_14(x) (x) PDK_PP_SEQ_SPLIT_13
# define PDK_PP_SEQ_SPLIT_15(x) (x) PDK_PP_SEQ_SPLIT_14
# define PDK_PP_SEQ_SPLIT_16(x) (x) PDK_PP_SEQ_SPLIT_15
# define PDK_PP_SEQ_SPLIT_17(x) (x) PDK_PP_SEQ_SPLIT_16
# define PDK_PP_SEQ_SPLIT_18(x) (x) PDK_PP_SEQ_SPLIT_17
# define PDK_PP_SEQ_SPLIT_19(x) (x) PDK_PP_SEQ_SPLIT_18
# define PDK_PP_SEQ_SPLIT_20(x) (x) PDK_PP_SEQ_SPLIT_19
# define PDK_PP_SEQ_SPLIT_21(x) (x) PDK_PP_SEQ_SPLIT_20
# define PDK_PP_SEQ_SPLIT_22(x) (x) PDK_PP_SEQ_SPLIT_21
# define PDK_PP_SEQ_SPLIT_23(x) (x) PDK_PP_SEQ_SPLIT_22
# define PDK_PP_SEQ_SPLIT_24(x) (x) PDK_PP_SEQ_SPLIT_23
# define PDK_PP_SEQ_SPLIT_25(x) (x) PDK_PP_SEQ_SPLIT_24
# define PDK_PP_SEQ_SPLIT_26(x) (x) PDK_PP_SEQ_SPLIT_25
# define PDK_PP_SEQ_SPLIT_27(x) (x) PDK_PP_SEQ_SPLIT_26
# define PDK_PP_SEQ_SPLIT_28(x) (x) PDK_PP_SEQ_SPLIT_27
# define PDK_PP_SEQ_SPLIT_29(x) (x) PDK_PP_SEQ_SPLIT_28
# define PDK_PP_SEQ_SPLIT_30(x) (x) PDK_PP_SEQ_SPLIT_29
# define PDK_PP_SEQ_SPLIT_31(x) (x) PDK_PP_SEQ_SPLIT_30
# define PDK_PP_SEQ_SPLIT_32(x) (x) PDK_PP_SEQ_SPLIT_31
# define PDK_PP_SEQ_SPLIT_33(x) (x) PDK_PP_SEQ_SPLIT_32
# define PDK_PP_SEQ_SPLIT_34(x) (x) PDK_PP_SEQ_SPLIT_33
# define PDK_PP_SEQ_SPLIT_35(x) (x) PDK_PP_SEQ_SPLIT_34
# define PDK_PP_SEQ_SPLIT_36(x) (x) PDK_PP_SEQ_SPLIT_35
# define PDK_PP_SEQ_SPLIT_37(x) (x) PDK_PP_SEQ_SPLIT_36
# define PDK_PP_SEQ_SPLIT_38(x) (x) PDK_PP_SEQ_SPLIT_37
# define PDK_PP_SEQ_SPLIT_39(x) (x) PDK_PP_SEQ_SPLIT_38
# define PDK_PP_SEQ_SPLIT_40(x) (x) PDK_PP_SEQ_SPLIT_39
# define PDK_PP_SEQ_SPLIT_41(x) (x) PDK_PP_SEQ_SPLIT_40
# define PDK_PP_SEQ_SPLIT_42(x) (x) PDK_PP_SEQ_SPLIT_41
# define PDK_PP_SEQ_SPLIT_43(x) (x) PDK_PP_SEQ_SPLIT_42
# define PDK_PP_SEQ_SPLIT_44(x) (x) PDK_PP_SEQ_SPLIT_43
# define PDK_PP_SEQ_SPLIT_45(x) (x) PDK_PP_SEQ_SPLIT_44
# define PDK_PP_SEQ_SPLIT_46(x) (x) PDK_PP_SEQ_SPLIT_45
# define PDK_PP_SEQ_SPLIT_47(x) (x) PDK_PP_SEQ_SPLIT_46
# define PDK_PP_SEQ_SPLIT_48(x) (x) PDK_PP_SEQ_SPLIT_47
# define PDK_PP_SEQ_SPLIT_49(x) (x) PDK_PP_SEQ_SPLIT_48
# define PDK_PP_SEQ_SPLIT_50(x) (x) PDK_PP_SEQ_SPLIT_49
# define PDK_PP_SEQ_SPLIT_51(x) (x) PDK_PP_SEQ_SPLIT_50
# define PDK_PP_SEQ_SPLIT_52(x) (x) PDK_PP_SEQ_SPLIT_51
# define PDK_PP_SEQ_SPLIT_53(x) (x) PDK_PP_SEQ_SPLIT_52
# define PDK_PP_SEQ_SPLIT_54(x) (x) PDK_PP_SEQ_SPLIT_53
# define PDK_PP_SEQ_SPLIT_55(x) (x) PDK_PP_SEQ_SPLIT_54
# define PDK_PP_SEQ_SPLIT_56(x) (x) PDK_PP_SEQ_SPLIT_55
# define PDK_PP_SEQ_SPLIT_57(x) (x) PDK_PP_SEQ_SPLIT_56
# define PDK_PP_SEQ_SPLIT_58(x) (x) PDK_PP_SEQ_SPLIT_57
# define PDK_PP_SEQ_SPLIT_59(x) (x) PDK_PP_SEQ_SPLIT_58
# define PDK_PP_SEQ_SPLIT_60(x) (x) PDK_PP_SEQ_SPLIT_59
# define PDK_PP_SEQ_SPLIT_61(x) (x) PDK_PP_SEQ_SPLIT_60
# define PDK_PP_SEQ_SPLIT_62(x) (x) PDK_PP_SEQ_SPLIT_61
# define PDK_PP_SEQ_SPLIT_63(x) (x) PDK_PP_SEQ_SPLIT_62
# define PDK_PP_SEQ_SPLIT_64(x) (x) PDK_PP_SEQ_SPLIT_63
# define PDK_PP_SEQ_SPLIT_65(x) (x) PDK_PP_SEQ_SPLIT_64
# define PDK_PP_SEQ_SPLIT_66(x) (x) PDK_PP_SEQ_SPLIT_65
# define PDK_PP_SEQ_SPLIT_67(x) (x) PDK_PP_SEQ_SPLIT_66
# define PDK_PP_SEQ_SPLIT_68(x) (x) PDK_PP_SEQ_SPLIT_67
# define PDK_PP_SEQ_SPLIT_69(x) (x) PDK_PP_SEQ_SPLIT_68
# define PDK_PP_SEQ_SPLIT_70(x) (x) PDK_PP_SEQ_SPLIT_69
# define PDK_PP_SEQ_SPLIT_71(x) (x) PDK_PP_SEQ_SPLIT_70
# define PDK_PP_SEQ_SPLIT_72(x) (x) PDK_PP_SEQ_SPLIT_71
# define PDK_PP_SEQ_SPLIT_73(x) (x) PDK_PP_SEQ_SPLIT_72
# define PDK_PP_SEQ_SPLIT_74(x) (x) PDK_PP_SEQ_SPLIT_73
# define PDK_PP_SEQ_SPLIT_75(x) (x) PDK_PP_SEQ_SPLIT_74
# define PDK_PP_SEQ_SPLIT_76(x) (x) PDK_PP_SEQ_SPLIT_75
# define PDK_PP_SEQ_SPLIT_77(x) (x) PDK_PP_SEQ_SPLIT_76
# define PDK_PP_SEQ_SPLIT_78(x) (x) PDK_PP_SEQ_SPLIT_77
# define PDK_PP_SEQ_SPLIT_79(x) (x) PDK_PP_SEQ_SPLIT_78
# define PDK_PP_SEQ_SPLIT_80(x) (x) PDK_PP_SEQ_SPLIT_79
# define PDK_PP_SEQ_SPLIT_81(x) (x) PDK_PP_SEQ_SPLIT_80
# define PDK_PP_SEQ_SPLIT_82(x) (x) PDK_PP_SEQ_SPLIT_81
# define PDK_PP_SEQ_SPLIT_83(x) (x) PDK_PP_SEQ_SPLIT_82
# define PDK_PP_SEQ_SPLIT_84(x) (x) PDK_PP_SEQ_SPLIT_83
# define PDK_PP_SEQ_SPLIT_85(x) (x) PDK_PP_SEQ_SPLIT_84
# define PDK_PP_SEQ_SPLIT_86(x) (x) PDK_PP_SEQ_SPLIT_85
# define PDK_PP_SEQ_SPLIT_87(x) (x) PDK_PP_SEQ_SPLIT_86
# define PDK_PP_SEQ_SPLIT_88(x) (x) PDK_PP_SEQ_SPLIT_87
# define PDK_PP_SEQ_SPLIT_89(x) (x) PDK_PP_SEQ_SPLIT_88
# define PDK_PP_SEQ_SPLIT_90(x) (x) PDK_PP_SEQ_SPLIT_89
# define PDK_PP_SEQ_SPLIT_91(x) (x) PDK_PP_SEQ_SPLIT_90
# define PDK_PP_SEQ_SPLIT_92(x) (x) PDK_PP_SEQ_SPLIT_91
# define PDK_PP_SEQ_SPLIT_93(x) (x) PDK_PP_SEQ_SPLIT_92
# define PDK_PP_SEQ_SPLIT_94(x) (x) PDK_PP_SEQ_SPLIT_93
# define PDK_PP_SEQ_SPLIT_95(x) (x) PDK_PP_SEQ_SPLIT_94
# define PDK_PP_SEQ_SPLIT_96(x) (x) PDK_PP_SEQ_SPLIT_95
# define PDK_PP_SEQ_SPLIT_97(x) (x) PDK_PP_SEQ_SPLIT_96
# define PDK_PP_SEQ_SPLIT_98(x) (x) PDK_PP_SEQ_SPLIT_97
# define PDK_PP_SEQ_SPLIT_99(x) (x) PDK_PP_SEQ_SPLIT_98
# define PDK_PP_SEQ_SPLIT_100(x) (x) PDK_PP_SEQ_SPLIT_99
# define PDK_PP_SEQ_SPLIT_101(x) (x) PDK_PP_SEQ_SPLIT_100
# define PDK_PP_SEQ_SPLIT_102(x) (x) PDK_PP_SEQ_SPLIT_101
# define PDK_PP_SEQ_SPLIT_103(x) (x) PDK_PP_SEQ_SPLIT_102
# define PDK_PP_SEQ_SPLIT_104(x) (x) PDK_PP_SEQ_SPLIT_103
# define PDK_PP_SEQ_SPLIT_105(x) (x) PDK_PP_SEQ_SPLIT_104
# define PDK_PP_SEQ_SPLIT_106(x) (x) PDK_PP_SEQ_SPLIT_105
# define PDK_PP_SEQ_SPLIT_107(x) (x) PDK_PP_SEQ_SPLIT_106
# define PDK_PP_SEQ_SPLIT_108(x) (x) PDK_PP_SEQ_SPLIT_107
# define PDK_PP_SEQ_SPLIT_109(x) (x) PDK_PP_SEQ_SPLIT_108
# define PDK_PP_SEQ_SPLIT_110(x) (x) PDK_PP_SEQ_SPLIT_109
# define PDK_PP_SEQ_SPLIT_111(x) (x) PDK_PP_SEQ_SPLIT_110
# define PDK_PP_SEQ_SPLIT_112(x) (x) PDK_PP_SEQ_SPLIT_111
# define PDK_PP_SEQ_SPLIT_113(x) (x) PDK_PP_SEQ_SPLIT_112
# define PDK_PP_SEQ_SPLIT_114(x) (x) PDK_PP_SEQ_SPLIT_113
# define PDK_PP_SEQ_SPLIT_115(x) (x) PDK_PP_SEQ_SPLIT_114
# define PDK_PP_SEQ_SPLIT_116(x) (x) PDK_PP_SEQ_SPLIT_115
# define PDK_PP_SEQ_SPLIT_117(x) (x) PDK_PP_SEQ_SPLIT_116
# define PDK_PP_SEQ_SPLIT_118(x) (x) PDK_PP_SEQ_SPLIT_117
# define PDK_PP_SEQ_SPLIT_119(x) (x) PDK_PP_SEQ_SPLIT_118
# define PDK_PP_SEQ_SPLIT_120(x) (x) PDK_PP_SEQ_SPLIT_119
# define PDK_PP_SEQ_SPLIT_121(x) (x) PDK_PP_SEQ_SPLIT_120
# define PDK_PP_SEQ_SPLIT_122(x) (x) PDK_PP_SEQ_SPLIT_121
# define PDK_PP_SEQ_SPLIT_123(x) (x) PDK_PP_SEQ_SPLIT_122
# define PDK_PP_SEQ_SPLIT_124(x) (x) PDK_PP_SEQ_SPLIT_123
# define PDK_PP_SEQ_SPLIT_125(x) (x) PDK_PP_SEQ_SPLIT_124
# define PDK_PP_SEQ_SPLIT_126(x) (x) PDK_PP_SEQ_SPLIT_125
# define PDK_PP_SEQ_SPLIT_127(x) (x) PDK_PP_SEQ_SPLIT_126
# define PDK_PP_SEQ_SPLIT_128(x) (x) PDK_PP_SEQ_SPLIT_127
# define PDK_PP_SEQ_SPLIT_129(x) (x) PDK_PP_SEQ_SPLIT_128
# define PDK_PP_SEQ_SPLIT_130(x) (x) PDK_PP_SEQ_SPLIT_129
# define PDK_PP_SEQ_SPLIT_131(x) (x) PDK_PP_SEQ_SPLIT_130
# define PDK_PP_SEQ_SPLIT_132(x) (x) PDK_PP_SEQ_SPLIT_131
# define PDK_PP_SEQ_SPLIT_133(x) (x) PDK_PP_SEQ_SPLIT_132
# define PDK_PP_SEQ_SPLIT_134(x) (x) PDK_PP_SEQ_SPLIT_133
# define PDK_PP_SEQ_SPLIT_135(x) (x) PDK_PP_SEQ_SPLIT_134
# define PDK_PP_SEQ_SPLIT_136(x) (x) PDK_PP_SEQ_SPLIT_135
# define PDK_PP_SEQ_SPLIT_137(x) (x) PDK_PP_SEQ_SPLIT_136
# define PDK_PP_SEQ_SPLIT_138(x) (x) PDK_PP_SEQ_SPLIT_137
# define PDK_PP_SEQ_SPLIT_139(x) (x) PDK_PP_SEQ_SPLIT_138
# define PDK_PP_SEQ_SPLIT_140(x) (x) PDK_PP_SEQ_SPLIT_139
# define PDK_PP_SEQ_SPLIT_141(x) (x) PDK_PP_SEQ_SPLIT_140
# define PDK_PP_SEQ_SPLIT_142(x) (x) PDK_PP_SEQ_SPLIT_141
# define PDK_PP_SEQ_SPLIT_143(x) (x) PDK_PP_SEQ_SPLIT_142
# define PDK_PP_SEQ_SPLIT_144(x) (x) PDK_PP_SEQ_SPLIT_143
# define PDK_PP_SEQ_SPLIT_145(x) (x) PDK_PP_SEQ_SPLIT_144
# define PDK_PP_SEQ_SPLIT_146(x) (x) PDK_PP_SEQ_SPLIT_145
# define PDK_PP_SEQ_SPLIT_147(x) (x) PDK_PP_SEQ_SPLIT_146
# define PDK_PP_SEQ_SPLIT_148(x) (x) PDK_PP_SEQ_SPLIT_147
# define PDK_PP_SEQ_SPLIT_149(x) (x) PDK_PP_SEQ_SPLIT_148
# define PDK_PP_SEQ_SPLIT_150(x) (x) PDK_PP_SEQ_SPLIT_149
# define PDK_PP_SEQ_SPLIT_151(x) (x) PDK_PP_SEQ_SPLIT_150
# define PDK_PP_SEQ_SPLIT_152(x) (x) PDK_PP_SEQ_SPLIT_151
# define PDK_PP_SEQ_SPLIT_153(x) (x) PDK_PP_SEQ_SPLIT_152
# define PDK_PP_SEQ_SPLIT_154(x) (x) PDK_PP_SEQ_SPLIT_153
# define PDK_PP_SEQ_SPLIT_155(x) (x) PDK_PP_SEQ_SPLIT_154
# define PDK_PP_SEQ_SPLIT_156(x) (x) PDK_PP_SEQ_SPLIT_155
# define PDK_PP_SEQ_SPLIT_157(x) (x) PDK_PP_SEQ_SPLIT_156
# define PDK_PP_SEQ_SPLIT_158(x) (x) PDK_PP_SEQ_SPLIT_157
# define PDK_PP_SEQ_SPLIT_159(x) (x) PDK_PP_SEQ_SPLIT_158
# define PDK_PP_SEQ_SPLIT_160(x) (x) PDK_PP_SEQ_SPLIT_159
# define PDK_PP_SEQ_SPLIT_161(x) (x) PDK_PP_SEQ_SPLIT_160
# define PDK_PP_SEQ_SPLIT_162(x) (x) PDK_PP_SEQ_SPLIT_161
# define PDK_PP_SEQ_SPLIT_163(x) (x) PDK_PP_SEQ_SPLIT_162
# define PDK_PP_SEQ_SPLIT_164(x) (x) PDK_PP_SEQ_SPLIT_163
# define PDK_PP_SEQ_SPLIT_165(x) (x) PDK_PP_SEQ_SPLIT_164
# define PDK_PP_SEQ_SPLIT_166(x) (x) PDK_PP_SEQ_SPLIT_165
# define PDK_PP_SEQ_SPLIT_167(x) (x) PDK_PP_SEQ_SPLIT_166
# define PDK_PP_SEQ_SPLIT_168(x) (x) PDK_PP_SEQ_SPLIT_167
# define PDK_PP_SEQ_SPLIT_169(x) (x) PDK_PP_SEQ_SPLIT_168
# define PDK_PP_SEQ_SPLIT_170(x) (x) PDK_PP_SEQ_SPLIT_169
# define PDK_PP_SEQ_SPLIT_171(x) (x) PDK_PP_SEQ_SPLIT_170
# define PDK_PP_SEQ_SPLIT_172(x) (x) PDK_PP_SEQ_SPLIT_171
# define PDK_PP_SEQ_SPLIT_173(x) (x) PDK_PP_SEQ_SPLIT_172
# define PDK_PP_SEQ_SPLIT_174(x) (x) PDK_PP_SEQ_SPLIT_173
# define PDK_PP_SEQ_SPLIT_175(x) (x) PDK_PP_SEQ_SPLIT_174
# define PDK_PP_SEQ_SPLIT_176(x) (x) PDK_PP_SEQ_SPLIT_175
# define PDK_PP_SEQ_SPLIT_177(x) (x) PDK_PP_SEQ_SPLIT_176
# define PDK_PP_SEQ_SPLIT_178(x) (x) PDK_PP_SEQ_SPLIT_177
# define PDK_PP_SEQ_SPLIT_179(x) (x) PDK_PP_SEQ_SPLIT_178
# define PDK_PP_SEQ_SPLIT_180(x) (x) PDK_PP_SEQ_SPLIT_179
# define PDK_PP_SEQ_SPLIT_181(x) (x) PDK_PP_SEQ_SPLIT_180
# define PDK_PP_SEQ_SPLIT_182(x) (x) PDK_PP_SEQ_SPLIT_181
# define PDK_PP_SEQ_SPLIT_183(x) (x) PDK_PP_SEQ_SPLIT_182
# define PDK_PP_SEQ_SPLIT_184(x) (x) PDK_PP_SEQ_SPLIT_183
# define PDK_PP_SEQ_SPLIT_185(x) (x) PDK_PP_SEQ_SPLIT_184
# define PDK_PP_SEQ_SPLIT_186(x) (x) PDK_PP_SEQ_SPLIT_185
# define PDK_PP_SEQ_SPLIT_187(x) (x) PDK_PP_SEQ_SPLIT_186
# define PDK_PP_SEQ_SPLIT_188(x) (x) PDK_PP_SEQ_SPLIT_187
# define PDK_PP_SEQ_SPLIT_189(x) (x) PDK_PP_SEQ_SPLIT_188
# define PDK_PP_SEQ_SPLIT_190(x) (x) PDK_PP_SEQ_SPLIT_189
# define PDK_PP_SEQ_SPLIT_191(x) (x) PDK_PP_SEQ_SPLIT_190
# define PDK_PP_SEQ_SPLIT_192(x) (x) PDK_PP_SEQ_SPLIT_191
# define PDK_PP_SEQ_SPLIT_193(x) (x) PDK_PP_SEQ_SPLIT_192
# define PDK_PP_SEQ_SPLIT_194(x) (x) PDK_PP_SEQ_SPLIT_193
# define PDK_PP_SEQ_SPLIT_195(x) (x) PDK_PP_SEQ_SPLIT_194
# define PDK_PP_SEQ_SPLIT_196(x) (x) PDK_PP_SEQ_SPLIT_195
# define PDK_PP_SEQ_SPLIT_197(x) (x) PDK_PP_SEQ_SPLIT_196
# define PDK_PP_SEQ_SPLIT_198(x) (x) PDK_PP_SEQ_SPLIT_197
# define PDK_PP_SEQ_SPLIT_199(x) (x) PDK_PP_SEQ_SPLIT_198
# define PDK_PP_SEQ_SPLIT_200(x) (x) PDK_PP_SEQ_SPLIT_199
# define PDK_PP_SEQ_SPLIT_201(x) (x) PDK_PP_SEQ_SPLIT_200
# define PDK_PP_SEQ_SPLIT_202(x) (x) PDK_PP_SEQ_SPLIT_201
# define PDK_PP_SEQ_SPLIT_203(x) (x) PDK_PP_SEQ_SPLIT_202
# define PDK_PP_SEQ_SPLIT_204(x) (x) PDK_PP_SEQ_SPLIT_203
# define PDK_PP_SEQ_SPLIT_205(x) (x) PDK_PP_SEQ_SPLIT_204
# define PDK_PP_SEQ_SPLIT_206(x) (x) PDK_PP_SEQ_SPLIT_205
# define PDK_PP_SEQ_SPLIT_207(x) (x) PDK_PP_SEQ_SPLIT_206
# define PDK_PP_SEQ_SPLIT_208(x) (x) PDK_PP_SEQ_SPLIT_207
# define PDK_PP_SEQ_SPLIT_209(x) (x) PDK_PP_SEQ_SPLIT_208
# define PDK_PP_SEQ_SPLIT_210(x) (x) PDK_PP_SEQ_SPLIT_209
# define PDK_PP_SEQ_SPLIT_211(x) (x) PDK_PP_SEQ_SPLIT_210
# define PDK_PP_SEQ_SPLIT_212(x) (x) PDK_PP_SEQ_SPLIT_211
# define PDK_PP_SEQ_SPLIT_213(x) (x) PDK_PP_SEQ_SPLIT_212
# define PDK_PP_SEQ_SPLIT_214(x) (x) PDK_PP_SEQ_SPLIT_213
# define PDK_PP_SEQ_SPLIT_215(x) (x) PDK_PP_SEQ_SPLIT_214
# define PDK_PP_SEQ_SPLIT_216(x) (x) PDK_PP_SEQ_SPLIT_215
# define PDK_PP_SEQ_SPLIT_217(x) (x) PDK_PP_SEQ_SPLIT_216
# define PDK_PP_SEQ_SPLIT_218(x) (x) PDK_PP_SEQ_SPLIT_217
# define PDK_PP_SEQ_SPLIT_219(x) (x) PDK_PP_SEQ_SPLIT_218
# define PDK_PP_SEQ_SPLIT_220(x) (x) PDK_PP_SEQ_SPLIT_219
# define PDK_PP_SEQ_SPLIT_221(x) (x) PDK_PP_SEQ_SPLIT_220
# define PDK_PP_SEQ_SPLIT_222(x) (x) PDK_PP_SEQ_SPLIT_221
# define PDK_PP_SEQ_SPLIT_223(x) (x) PDK_PP_SEQ_SPLIT_222
# define PDK_PP_SEQ_SPLIT_224(x) (x) PDK_PP_SEQ_SPLIT_223
# define PDK_PP_SEQ_SPLIT_225(x) (x) PDK_PP_SEQ_SPLIT_224
# define PDK_PP_SEQ_SPLIT_226(x) (x) PDK_PP_SEQ_SPLIT_225
# define PDK_PP_SEQ_SPLIT_227(x) (x) PDK_PP_SEQ_SPLIT_226
# define PDK_PP_SEQ_SPLIT_228(x) (x) PDK_PP_SEQ_SPLIT_227
# define PDK_PP_SEQ_SPLIT_229(x) (x) PDK_PP_SEQ_SPLIT_228
# define PDK_PP_SEQ_SPLIT_230(x) (x) PDK_PP_SEQ_SPLIT_229
# define PDK_PP_SEQ_SPLIT_231(x) (x) PDK_PP_SEQ_SPLIT_230
# define PDK_PP_SEQ_SPLIT_232(x) (x) PDK_PP_SEQ_SPLIT_231
# define PDK_PP_SEQ_SPLIT_233(x) (x) PDK_PP_SEQ_SPLIT_232
# define PDK_PP_SEQ_SPLIT_234(x) (x) PDK_PP_SEQ_SPLIT_233
# define PDK_PP_SEQ_SPLIT_235(x) (x) PDK_PP_SEQ_SPLIT_234
# define PDK_PP_SEQ_SPLIT_236(x) (x) PDK_PP_SEQ_SPLIT_235
# define PDK_PP_SEQ_SPLIT_237(x) (x) PDK_PP_SEQ_SPLIT_236
# define PDK_PP_SEQ_SPLIT_238(x) (x) PDK_PP_SEQ_SPLIT_237
# define PDK_PP_SEQ_SPLIT_239(x) (x) PDK_PP_SEQ_SPLIT_238
# define PDK_PP_SEQ_SPLIT_240(x) (x) PDK_PP_SEQ_SPLIT_239
# define PDK_PP_SEQ_SPLIT_241(x) (x) PDK_PP_SEQ_SPLIT_240
# define PDK_PP_SEQ_SPLIT_242(x) (x) PDK_PP_SEQ_SPLIT_241
# define PDK_PP_SEQ_SPLIT_243(x) (x) PDK_PP_SEQ_SPLIT_242
# define PDK_PP_SEQ_SPLIT_244(x) (x) PDK_PP_SEQ_SPLIT_243
# define PDK_PP_SEQ_SPLIT_245(x) (x) PDK_PP_SEQ_SPLIT_244
# define PDK_PP_SEQ_SPLIT_246(x) (x) PDK_PP_SEQ_SPLIT_245
# define PDK_PP_SEQ_SPLIT_247(x) (x) PDK_PP_SEQ_SPLIT_246
# define PDK_PP_SEQ_SPLIT_248(x) (x) PDK_PP_SEQ_SPLIT_247
# define PDK_PP_SEQ_SPLIT_249(x) (x) PDK_PP_SEQ_SPLIT_248
# define PDK_PP_SEQ_SPLIT_250(x) (x) PDK_PP_SEQ_SPLIT_249
# define PDK_PP_SEQ_SPLIT_251(x) (x) PDK_PP_SEQ_SPLIT_250
# define PDK_PP_SEQ_SPLIT_252(x) (x) PDK_PP_SEQ_SPLIT_251
# define PDK_PP_SEQ_SPLIT_253(x) (x) PDK_PP_SEQ_SPLIT_252
# define PDK_PP_SEQ_SPLIT_254(x) (x) PDK_PP_SEQ_SPLIT_253
# define PDK_PP_SEQ_SPLIT_255(x) (x) PDK_PP_SEQ_SPLIT_254
# define PDK_PP_SEQ_SPLIT_256(x) (x) PDK_PP_SEQ_SPLIT_255

#endif // PDK_STDEXT_PREPROCESSOR_SEQ_INTERNAL_SPLIT_H
