// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/01/15.

// ****************************************************************************
// *                                                                          *
// *     (C) Copyright Paul Mensonides 2002-2011.                             *
// *     (C) Copyright Edward Diener 2011.                                    *
// *     Distributed under the Boost Software License, Version 1.0. (See      *
// *     accompanying file LICENSE_1_0.txt or copy at                         *
// *     http://www.boost.org/LICENSE_1_0.txt)                                *
// *                                                                          *
// ****************************************************************************
// 
// See http://www.boost.org for most recent version.

#ifndef PDK_STDEXT_PREPROCESSOR_FACILITIES_INTERCEPT_H
#define PDK_STDEXT_PREPROCESSOR_FACILITIES_INTERCEPT_H

// PDK_PP_INTERCEPT
# define PDK_PP_INTERCEPT PDK_PP_INTERCEPT_

# define PDK_PP_INTERCEPT_0
# define PDK_PP_INTERCEPT_1
# define PDK_PP_INTERCEPT_2
# define PDK_PP_INTERCEPT_3
# define PDK_PP_INTERCEPT_4
# define PDK_PP_INTERCEPT_5
# define PDK_PP_INTERCEPT_6
# define PDK_PP_INTERCEPT_7
# define PDK_PP_INTERCEPT_8
# define PDK_PP_INTERCEPT_9
# define PDK_PP_INTERCEPT_10
# define PDK_PP_INTERCEPT_11
# define PDK_PP_INTERCEPT_12
# define PDK_PP_INTERCEPT_13
# define PDK_PP_INTERCEPT_14
# define PDK_PP_INTERCEPT_15
# define PDK_PP_INTERCEPT_16
# define PDK_PP_INTERCEPT_17
# define PDK_PP_INTERCEPT_18
# define PDK_PP_INTERCEPT_19
# define PDK_PP_INTERCEPT_20
# define PDK_PP_INTERCEPT_21
# define PDK_PP_INTERCEPT_22
# define PDK_PP_INTERCEPT_23
# define PDK_PP_INTERCEPT_24
# define PDK_PP_INTERCEPT_25
# define PDK_PP_INTERCEPT_26
# define PDK_PP_INTERCEPT_27
# define PDK_PP_INTERCEPT_28
# define PDK_PP_INTERCEPT_29
# define PDK_PP_INTERCEPT_30
# define PDK_PP_INTERCEPT_31
# define PDK_PP_INTERCEPT_32
# define PDK_PP_INTERCEPT_33
# define PDK_PP_INTERCEPT_34
# define PDK_PP_INTERCEPT_35
# define PDK_PP_INTERCEPT_36
# define PDK_PP_INTERCEPT_37
# define PDK_PP_INTERCEPT_38
# define PDK_PP_INTERCEPT_39
# define PDK_PP_INTERCEPT_40
# define PDK_PP_INTERCEPT_41
# define PDK_PP_INTERCEPT_42
# define PDK_PP_INTERCEPT_43
# define PDK_PP_INTERCEPT_44
# define PDK_PP_INTERCEPT_45
# define PDK_PP_INTERCEPT_46
# define PDK_PP_INTERCEPT_47
# define PDK_PP_INTERCEPT_48
# define PDK_PP_INTERCEPT_49
# define PDK_PP_INTERCEPT_50
# define PDK_PP_INTERCEPT_51
# define PDK_PP_INTERCEPT_52
# define PDK_PP_INTERCEPT_53
# define PDK_PP_INTERCEPT_54
# define PDK_PP_INTERCEPT_55
# define PDK_PP_INTERCEPT_56
# define PDK_PP_INTERCEPT_57
# define PDK_PP_INTERCEPT_58
# define PDK_PP_INTERCEPT_59
# define PDK_PP_INTERCEPT_60
# define PDK_PP_INTERCEPT_61
# define PDK_PP_INTERCEPT_62
# define PDK_PP_INTERCEPT_63
# define PDK_PP_INTERCEPT_64
# define PDK_PP_INTERCEPT_65
# define PDK_PP_INTERCEPT_66
# define PDK_PP_INTERCEPT_67
# define PDK_PP_INTERCEPT_68
# define PDK_PP_INTERCEPT_69
# define PDK_PP_INTERCEPT_70
# define PDK_PP_INTERCEPT_71
# define PDK_PP_INTERCEPT_72
# define PDK_PP_INTERCEPT_73
# define PDK_PP_INTERCEPT_74
# define PDK_PP_INTERCEPT_75
# define PDK_PP_INTERCEPT_76
# define PDK_PP_INTERCEPT_77
# define PDK_PP_INTERCEPT_78
# define PDK_PP_INTERCEPT_79
# define PDK_PP_INTERCEPT_80
# define PDK_PP_INTERCEPT_81
# define PDK_PP_INTERCEPT_82
# define PDK_PP_INTERCEPT_83
# define PDK_PP_INTERCEPT_84
# define PDK_PP_INTERCEPT_85
# define PDK_PP_INTERCEPT_86
# define PDK_PP_INTERCEPT_87
# define PDK_PP_INTERCEPT_88
# define PDK_PP_INTERCEPT_89
# define PDK_PP_INTERCEPT_90
# define PDK_PP_INTERCEPT_91
# define PDK_PP_INTERCEPT_92
# define PDK_PP_INTERCEPT_93
# define PDK_PP_INTERCEPT_94
# define PDK_PP_INTERCEPT_95
# define PDK_PP_INTERCEPT_96
# define PDK_PP_INTERCEPT_97
# define PDK_PP_INTERCEPT_98
# define PDK_PP_INTERCEPT_99
# define PDK_PP_INTERCEPT_100
# define PDK_PP_INTERCEPT_101
# define PDK_PP_INTERCEPT_102
# define PDK_PP_INTERCEPT_103
# define PDK_PP_INTERCEPT_104
# define PDK_PP_INTERCEPT_105
# define PDK_PP_INTERCEPT_106
# define PDK_PP_INTERCEPT_107
# define PDK_PP_INTERCEPT_108
# define PDK_PP_INTERCEPT_109
# define PDK_PP_INTERCEPT_110
# define PDK_PP_INTERCEPT_111
# define PDK_PP_INTERCEPT_112
# define PDK_PP_INTERCEPT_113
# define PDK_PP_INTERCEPT_114
# define PDK_PP_INTERCEPT_115
# define PDK_PP_INTERCEPT_116
# define PDK_PP_INTERCEPT_117
# define PDK_PP_INTERCEPT_118
# define PDK_PP_INTERCEPT_119
# define PDK_PP_INTERCEPT_120
# define PDK_PP_INTERCEPT_121
# define PDK_PP_INTERCEPT_122
# define PDK_PP_INTERCEPT_123
# define PDK_PP_INTERCEPT_124
# define PDK_PP_INTERCEPT_125
# define PDK_PP_INTERCEPT_126
# define PDK_PP_INTERCEPT_127
# define PDK_PP_INTERCEPT_128
# define PDK_PP_INTERCEPT_129
# define PDK_PP_INTERCEPT_130
# define PDK_PP_INTERCEPT_131
# define PDK_PP_INTERCEPT_132
# define PDK_PP_INTERCEPT_133
# define PDK_PP_INTERCEPT_134
# define PDK_PP_INTERCEPT_135
# define PDK_PP_INTERCEPT_136
# define PDK_PP_INTERCEPT_137
# define PDK_PP_INTERCEPT_138
# define PDK_PP_INTERCEPT_139
# define PDK_PP_INTERCEPT_140
# define PDK_PP_INTERCEPT_141
# define PDK_PP_INTERCEPT_142
# define PDK_PP_INTERCEPT_143
# define PDK_PP_INTERCEPT_144
# define PDK_PP_INTERCEPT_145
# define PDK_PP_INTERCEPT_146
# define PDK_PP_INTERCEPT_147
# define PDK_PP_INTERCEPT_148
# define PDK_PP_INTERCEPT_149
# define PDK_PP_INTERCEPT_150
# define PDK_PP_INTERCEPT_151
# define PDK_PP_INTERCEPT_152
# define PDK_PP_INTERCEPT_153
# define PDK_PP_INTERCEPT_154
# define PDK_PP_INTERCEPT_155
# define PDK_PP_INTERCEPT_156
# define PDK_PP_INTERCEPT_157
# define PDK_PP_INTERCEPT_158
# define PDK_PP_INTERCEPT_159
# define PDK_PP_INTERCEPT_160
# define PDK_PP_INTERCEPT_161
# define PDK_PP_INTERCEPT_162
# define PDK_PP_INTERCEPT_163
# define PDK_PP_INTERCEPT_164
# define PDK_PP_INTERCEPT_165
# define PDK_PP_INTERCEPT_166
# define PDK_PP_INTERCEPT_167
# define PDK_PP_INTERCEPT_168
# define PDK_PP_INTERCEPT_169
# define PDK_PP_INTERCEPT_170
# define PDK_PP_INTERCEPT_171
# define PDK_PP_INTERCEPT_172
# define PDK_PP_INTERCEPT_173
# define PDK_PP_INTERCEPT_174
# define PDK_PP_INTERCEPT_175
# define PDK_PP_INTERCEPT_176
# define PDK_PP_INTERCEPT_177
# define PDK_PP_INTERCEPT_178
# define PDK_PP_INTERCEPT_179
# define PDK_PP_INTERCEPT_180
# define PDK_PP_INTERCEPT_181
# define PDK_PP_INTERCEPT_182
# define PDK_PP_INTERCEPT_183
# define PDK_PP_INTERCEPT_184
# define PDK_PP_INTERCEPT_185
# define PDK_PP_INTERCEPT_186
# define PDK_PP_INTERCEPT_187
# define PDK_PP_INTERCEPT_188
# define PDK_PP_INTERCEPT_189
# define PDK_PP_INTERCEPT_190
# define PDK_PP_INTERCEPT_191
# define PDK_PP_INTERCEPT_192
# define PDK_PP_INTERCEPT_193
# define PDK_PP_INTERCEPT_194
# define PDK_PP_INTERCEPT_195
# define PDK_PP_INTERCEPT_196
# define PDK_PP_INTERCEPT_197
# define PDK_PP_INTERCEPT_198
# define PDK_PP_INTERCEPT_199
# define PDK_PP_INTERCEPT_200
# define PDK_PP_INTERCEPT_201
# define PDK_PP_INTERCEPT_202
# define PDK_PP_INTERCEPT_203
# define PDK_PP_INTERCEPT_204
# define PDK_PP_INTERCEPT_205
# define PDK_PP_INTERCEPT_206
# define PDK_PP_INTERCEPT_207
# define PDK_PP_INTERCEPT_208
# define PDK_PP_INTERCEPT_209
# define PDK_PP_INTERCEPT_210
# define PDK_PP_INTERCEPT_211
# define PDK_PP_INTERCEPT_212
# define PDK_PP_INTERCEPT_213
# define PDK_PP_INTERCEPT_214
# define PDK_PP_INTERCEPT_215
# define PDK_PP_INTERCEPT_216
# define PDK_PP_INTERCEPT_217
# define PDK_PP_INTERCEPT_218
# define PDK_PP_INTERCEPT_219
# define PDK_PP_INTERCEPT_220
# define PDK_PP_INTERCEPT_221
# define PDK_PP_INTERCEPT_222
# define PDK_PP_INTERCEPT_223
# define PDK_PP_INTERCEPT_224
# define PDK_PP_INTERCEPT_225
# define PDK_PP_INTERCEPT_226
# define PDK_PP_INTERCEPT_227
# define PDK_PP_INTERCEPT_228
# define PDK_PP_INTERCEPT_229
# define PDK_PP_INTERCEPT_230
# define PDK_PP_INTERCEPT_231
# define PDK_PP_INTERCEPT_232
# define PDK_PP_INTERCEPT_233
# define PDK_PP_INTERCEPT_234
# define PDK_PP_INTERCEPT_235
# define PDK_PP_INTERCEPT_236
# define PDK_PP_INTERCEPT_237
# define PDK_PP_INTERCEPT_238
# define PDK_PP_INTERCEPT_239
# define PDK_PP_INTERCEPT_240
# define PDK_PP_INTERCEPT_241
# define PDK_PP_INTERCEPT_242
# define PDK_PP_INTERCEPT_243
# define PDK_PP_INTERCEPT_244
# define PDK_PP_INTERCEPT_245
# define PDK_PP_INTERCEPT_246
# define PDK_PP_INTERCEPT_247
# define PDK_PP_INTERCEPT_248
# define PDK_PP_INTERCEPT_249
# define PDK_PP_INTERCEPT_250
# define PDK_PP_INTERCEPT_251
# define PDK_PP_INTERCEPT_252
# define PDK_PP_INTERCEPT_253
# define PDK_PP_INTERCEPT_254
# define PDK_PP_INTERCEPT_255
# define PDK_PP_INTERCEPT_256

#endif // PDK_STDEXT_PREPROCESSOR_FACILITIES_INTERCEPT_H
