// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/01/15.

// ****************************************************************************
// *                                                                          *
// *     (C) Copyright Paul Mensonides 2002-2011.                             *
// *     (C) Copyright Edward Diener 2011.                                    *
// *     Distributed under the Boost Software License, Version 1.0. (See      *
// *     accompanying file LICENSE_1_0.txt or copy at                         *
// *     http://www.boost.org/LICENSE_1_0.txt)                                *
// *                                                                          *
// ****************************************************************************
// 
// See http://www.boost.org for most recent version.

#ifndef PDK_STDEXT_PREPROCESSOR_SEQ_ENUM_H
#define PDK_STDEXT_PREPROCESSOR_SEQ_ENUM_H

#include "pdk/stdext/preprocessor/Cat.h"
#include "pdk/stdext/preprocessor/config/Config.h"
#include "pdk/stdext/preprocessor/seq/Size.h"

// PDK_PP_SEQ_ENUM
# if PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_EDG()
#    define PDK_PP_SEQ_ENUM(seq) PDK_PP_SEQ_ENUM_I(seq)
#    define PDK_PP_SEQ_ENUM_I(seq) PDK_PP_CAT(PDK_PP_SEQ_ENUM_, PDK_PP_SEQ_SIZE(seq)) seq
# elif PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_MWCC()
#    define PDK_PP_SEQ_ENUM(seq) PDK_PP_SEQ_ENUM_I(PDK_PP_SEQ_SIZE(seq), seq)
#    define PDK_PP_SEQ_ENUM_I(size, seq) PDK_PP_CAT(PDK_PP_SEQ_ENUM_, size) seq
# else
#    define PDK_PP_SEQ_ENUM(seq) PDK_PP_CAT(PDK_PP_SEQ_ENUM_, PDK_PP_SEQ_SIZE(seq)) seq
# endif

# define PDK_PP_SEQ_ENUM_1(x) x
# define PDK_PP_SEQ_ENUM_2(x) x, PDK_PP_SEQ_ENUM_1
# define PDK_PP_SEQ_ENUM_3(x) x, PDK_PP_SEQ_ENUM_2
# define PDK_PP_SEQ_ENUM_4(x) x, PDK_PP_SEQ_ENUM_3
# define PDK_PP_SEQ_ENUM_5(x) x, PDK_PP_SEQ_ENUM_4
# define PDK_PP_SEQ_ENUM_6(x) x, PDK_PP_SEQ_ENUM_5
# define PDK_PP_SEQ_ENUM_7(x) x, PDK_PP_SEQ_ENUM_6
# define PDK_PP_SEQ_ENUM_8(x) x, PDK_PP_SEQ_ENUM_7
# define PDK_PP_SEQ_ENUM_9(x) x, PDK_PP_SEQ_ENUM_8
# define PDK_PP_SEQ_ENUM_10(x) x, PDK_PP_SEQ_ENUM_9
# define PDK_PP_SEQ_ENUM_11(x) x, PDK_PP_SEQ_ENUM_10
# define PDK_PP_SEQ_ENUM_12(x) x, PDK_PP_SEQ_ENUM_11
# define PDK_PP_SEQ_ENUM_13(x) x, PDK_PP_SEQ_ENUM_12
# define PDK_PP_SEQ_ENUM_14(x) x, PDK_PP_SEQ_ENUM_13
# define PDK_PP_SEQ_ENUM_15(x) x, PDK_PP_SEQ_ENUM_14
# define PDK_PP_SEQ_ENUM_16(x) x, PDK_PP_SEQ_ENUM_15
# define PDK_PP_SEQ_ENUM_17(x) x, PDK_PP_SEQ_ENUM_16
# define PDK_PP_SEQ_ENUM_18(x) x, PDK_PP_SEQ_ENUM_17
# define PDK_PP_SEQ_ENUM_19(x) x, PDK_PP_SEQ_ENUM_18
# define PDK_PP_SEQ_ENUM_20(x) x, PDK_PP_SEQ_ENUM_19
# define PDK_PP_SEQ_ENUM_21(x) x, PDK_PP_SEQ_ENUM_20
# define PDK_PP_SEQ_ENUM_22(x) x, PDK_PP_SEQ_ENUM_21
# define PDK_PP_SEQ_ENUM_23(x) x, PDK_PP_SEQ_ENUM_22
# define PDK_PP_SEQ_ENUM_24(x) x, PDK_PP_SEQ_ENUM_23
# define PDK_PP_SEQ_ENUM_25(x) x, PDK_PP_SEQ_ENUM_24
# define PDK_PP_SEQ_ENUM_26(x) x, PDK_PP_SEQ_ENUM_25
# define PDK_PP_SEQ_ENUM_27(x) x, PDK_PP_SEQ_ENUM_26
# define PDK_PP_SEQ_ENUM_28(x) x, PDK_PP_SEQ_ENUM_27
# define PDK_PP_SEQ_ENUM_29(x) x, PDK_PP_SEQ_ENUM_28
# define PDK_PP_SEQ_ENUM_30(x) x, PDK_PP_SEQ_ENUM_29
# define PDK_PP_SEQ_ENUM_31(x) x, PDK_PP_SEQ_ENUM_30
# define PDK_PP_SEQ_ENUM_32(x) x, PDK_PP_SEQ_ENUM_31
# define PDK_PP_SEQ_ENUM_33(x) x, PDK_PP_SEQ_ENUM_32
# define PDK_PP_SEQ_ENUM_34(x) x, PDK_PP_SEQ_ENUM_33
# define PDK_PP_SEQ_ENUM_35(x) x, PDK_PP_SEQ_ENUM_34
# define PDK_PP_SEQ_ENUM_36(x) x, PDK_PP_SEQ_ENUM_35
# define PDK_PP_SEQ_ENUM_37(x) x, PDK_PP_SEQ_ENUM_36
# define PDK_PP_SEQ_ENUM_38(x) x, PDK_PP_SEQ_ENUM_37
# define PDK_PP_SEQ_ENUM_39(x) x, PDK_PP_SEQ_ENUM_38
# define PDK_PP_SEQ_ENUM_40(x) x, PDK_PP_SEQ_ENUM_39
# define PDK_PP_SEQ_ENUM_41(x) x, PDK_PP_SEQ_ENUM_40
# define PDK_PP_SEQ_ENUM_42(x) x, PDK_PP_SEQ_ENUM_41
# define PDK_PP_SEQ_ENUM_43(x) x, PDK_PP_SEQ_ENUM_42
# define PDK_PP_SEQ_ENUM_44(x) x, PDK_PP_SEQ_ENUM_43
# define PDK_PP_SEQ_ENUM_45(x) x, PDK_PP_SEQ_ENUM_44
# define PDK_PP_SEQ_ENUM_46(x) x, PDK_PP_SEQ_ENUM_45
# define PDK_PP_SEQ_ENUM_47(x) x, PDK_PP_SEQ_ENUM_46
# define PDK_PP_SEQ_ENUM_48(x) x, PDK_PP_SEQ_ENUM_47
# define PDK_PP_SEQ_ENUM_49(x) x, PDK_PP_SEQ_ENUM_48
# define PDK_PP_SEQ_ENUM_50(x) x, PDK_PP_SEQ_ENUM_49
# define PDK_PP_SEQ_ENUM_51(x) x, PDK_PP_SEQ_ENUM_50
# define PDK_PP_SEQ_ENUM_52(x) x, PDK_PP_SEQ_ENUM_51
# define PDK_PP_SEQ_ENUM_53(x) x, PDK_PP_SEQ_ENUM_52
# define PDK_PP_SEQ_ENUM_54(x) x, PDK_PP_SEQ_ENUM_53
# define PDK_PP_SEQ_ENUM_55(x) x, PDK_PP_SEQ_ENUM_54
# define PDK_PP_SEQ_ENUM_56(x) x, PDK_PP_SEQ_ENUM_55
# define PDK_PP_SEQ_ENUM_57(x) x, PDK_PP_SEQ_ENUM_56
# define PDK_PP_SEQ_ENUM_58(x) x, PDK_PP_SEQ_ENUM_57
# define PDK_PP_SEQ_ENUM_59(x) x, PDK_PP_SEQ_ENUM_58
# define PDK_PP_SEQ_ENUM_60(x) x, PDK_PP_SEQ_ENUM_59
# define PDK_PP_SEQ_ENUM_61(x) x, PDK_PP_SEQ_ENUM_60
# define PDK_PP_SEQ_ENUM_62(x) x, PDK_PP_SEQ_ENUM_61
# define PDK_PP_SEQ_ENUM_63(x) x, PDK_PP_SEQ_ENUM_62
# define PDK_PP_SEQ_ENUM_64(x) x, PDK_PP_SEQ_ENUM_63
# define PDK_PP_SEQ_ENUM_65(x) x, PDK_PP_SEQ_ENUM_64
# define PDK_PP_SEQ_ENUM_66(x) x, PDK_PP_SEQ_ENUM_65
# define PDK_PP_SEQ_ENUM_67(x) x, PDK_PP_SEQ_ENUM_66
# define PDK_PP_SEQ_ENUM_68(x) x, PDK_PP_SEQ_ENUM_67
# define PDK_PP_SEQ_ENUM_69(x) x, PDK_PP_SEQ_ENUM_68
# define PDK_PP_SEQ_ENUM_70(x) x, PDK_PP_SEQ_ENUM_69
# define PDK_PP_SEQ_ENUM_71(x) x, PDK_PP_SEQ_ENUM_70
# define PDK_PP_SEQ_ENUM_72(x) x, PDK_PP_SEQ_ENUM_71
# define PDK_PP_SEQ_ENUM_73(x) x, PDK_PP_SEQ_ENUM_72
# define PDK_PP_SEQ_ENUM_74(x) x, PDK_PP_SEQ_ENUM_73
# define PDK_PP_SEQ_ENUM_75(x) x, PDK_PP_SEQ_ENUM_74
# define PDK_PP_SEQ_ENUM_76(x) x, PDK_PP_SEQ_ENUM_75
# define PDK_PP_SEQ_ENUM_77(x) x, PDK_PP_SEQ_ENUM_76
# define PDK_PP_SEQ_ENUM_78(x) x, PDK_PP_SEQ_ENUM_77
# define PDK_PP_SEQ_ENUM_79(x) x, PDK_PP_SEQ_ENUM_78
# define PDK_PP_SEQ_ENUM_80(x) x, PDK_PP_SEQ_ENUM_79
# define PDK_PP_SEQ_ENUM_81(x) x, PDK_PP_SEQ_ENUM_80
# define PDK_PP_SEQ_ENUM_82(x) x, PDK_PP_SEQ_ENUM_81
# define PDK_PP_SEQ_ENUM_83(x) x, PDK_PP_SEQ_ENUM_82
# define PDK_PP_SEQ_ENUM_84(x) x, PDK_PP_SEQ_ENUM_83
# define PDK_PP_SEQ_ENUM_85(x) x, PDK_PP_SEQ_ENUM_84
# define PDK_PP_SEQ_ENUM_86(x) x, PDK_PP_SEQ_ENUM_85
# define PDK_PP_SEQ_ENUM_87(x) x, PDK_PP_SEQ_ENUM_86
# define PDK_PP_SEQ_ENUM_88(x) x, PDK_PP_SEQ_ENUM_87
# define PDK_PP_SEQ_ENUM_89(x) x, PDK_PP_SEQ_ENUM_88
# define PDK_PP_SEQ_ENUM_90(x) x, PDK_PP_SEQ_ENUM_89
# define PDK_PP_SEQ_ENUM_91(x) x, PDK_PP_SEQ_ENUM_90
# define PDK_PP_SEQ_ENUM_92(x) x, PDK_PP_SEQ_ENUM_91
# define PDK_PP_SEQ_ENUM_93(x) x, PDK_PP_SEQ_ENUM_92
# define PDK_PP_SEQ_ENUM_94(x) x, PDK_PP_SEQ_ENUM_93
# define PDK_PP_SEQ_ENUM_95(x) x, PDK_PP_SEQ_ENUM_94
# define PDK_PP_SEQ_ENUM_96(x) x, PDK_PP_SEQ_ENUM_95
# define PDK_PP_SEQ_ENUM_97(x) x, PDK_PP_SEQ_ENUM_96
# define PDK_PP_SEQ_ENUM_98(x) x, PDK_PP_SEQ_ENUM_97
# define PDK_PP_SEQ_ENUM_99(x) x, PDK_PP_SEQ_ENUM_98
# define PDK_PP_SEQ_ENUM_100(x) x, PDK_PP_SEQ_ENUM_99
# define PDK_PP_SEQ_ENUM_101(x) x, PDK_PP_SEQ_ENUM_100
# define PDK_PP_SEQ_ENUM_102(x) x, PDK_PP_SEQ_ENUM_101
# define PDK_PP_SEQ_ENUM_103(x) x, PDK_PP_SEQ_ENUM_102
# define PDK_PP_SEQ_ENUM_104(x) x, PDK_PP_SEQ_ENUM_103
# define PDK_PP_SEQ_ENUM_105(x) x, PDK_PP_SEQ_ENUM_104
# define PDK_PP_SEQ_ENUM_106(x) x, PDK_PP_SEQ_ENUM_105
# define PDK_PP_SEQ_ENUM_107(x) x, PDK_PP_SEQ_ENUM_106
# define PDK_PP_SEQ_ENUM_108(x) x, PDK_PP_SEQ_ENUM_107
# define PDK_PP_SEQ_ENUM_109(x) x, PDK_PP_SEQ_ENUM_108
# define PDK_PP_SEQ_ENUM_110(x) x, PDK_PP_SEQ_ENUM_109
# define PDK_PP_SEQ_ENUM_111(x) x, PDK_PP_SEQ_ENUM_110
# define PDK_PP_SEQ_ENUM_112(x) x, PDK_PP_SEQ_ENUM_111
# define PDK_PP_SEQ_ENUM_113(x) x, PDK_PP_SEQ_ENUM_112
# define PDK_PP_SEQ_ENUM_114(x) x, PDK_PP_SEQ_ENUM_113
# define PDK_PP_SEQ_ENUM_115(x) x, PDK_PP_SEQ_ENUM_114
# define PDK_PP_SEQ_ENUM_116(x) x, PDK_PP_SEQ_ENUM_115
# define PDK_PP_SEQ_ENUM_117(x) x, PDK_PP_SEQ_ENUM_116
# define PDK_PP_SEQ_ENUM_118(x) x, PDK_PP_SEQ_ENUM_117
# define PDK_PP_SEQ_ENUM_119(x) x, PDK_PP_SEQ_ENUM_118
# define PDK_PP_SEQ_ENUM_120(x) x, PDK_PP_SEQ_ENUM_119
# define PDK_PP_SEQ_ENUM_121(x) x, PDK_PP_SEQ_ENUM_120
# define PDK_PP_SEQ_ENUM_122(x) x, PDK_PP_SEQ_ENUM_121
# define PDK_PP_SEQ_ENUM_123(x) x, PDK_PP_SEQ_ENUM_122
# define PDK_PP_SEQ_ENUM_124(x) x, PDK_PP_SEQ_ENUM_123
# define PDK_PP_SEQ_ENUM_125(x) x, PDK_PP_SEQ_ENUM_124
# define PDK_PP_SEQ_ENUM_126(x) x, PDK_PP_SEQ_ENUM_125
# define PDK_PP_SEQ_ENUM_127(x) x, PDK_PP_SEQ_ENUM_126
# define PDK_PP_SEQ_ENUM_128(x) x, PDK_PP_SEQ_ENUM_127
# define PDK_PP_SEQ_ENUM_129(x) x, PDK_PP_SEQ_ENUM_128
# define PDK_PP_SEQ_ENUM_130(x) x, PDK_PP_SEQ_ENUM_129
# define PDK_PP_SEQ_ENUM_131(x) x, PDK_PP_SEQ_ENUM_130
# define PDK_PP_SEQ_ENUM_132(x) x, PDK_PP_SEQ_ENUM_131
# define PDK_PP_SEQ_ENUM_133(x) x, PDK_PP_SEQ_ENUM_132
# define PDK_PP_SEQ_ENUM_134(x) x, PDK_PP_SEQ_ENUM_133
# define PDK_PP_SEQ_ENUM_135(x) x, PDK_PP_SEQ_ENUM_134
# define PDK_PP_SEQ_ENUM_136(x) x, PDK_PP_SEQ_ENUM_135
# define PDK_PP_SEQ_ENUM_137(x) x, PDK_PP_SEQ_ENUM_136
# define PDK_PP_SEQ_ENUM_138(x) x, PDK_PP_SEQ_ENUM_137
# define PDK_PP_SEQ_ENUM_139(x) x, PDK_PP_SEQ_ENUM_138
# define PDK_PP_SEQ_ENUM_140(x) x, PDK_PP_SEQ_ENUM_139
# define PDK_PP_SEQ_ENUM_141(x) x, PDK_PP_SEQ_ENUM_140
# define PDK_PP_SEQ_ENUM_142(x) x, PDK_PP_SEQ_ENUM_141
# define PDK_PP_SEQ_ENUM_143(x) x, PDK_PP_SEQ_ENUM_142
# define PDK_PP_SEQ_ENUM_144(x) x, PDK_PP_SEQ_ENUM_143
# define PDK_PP_SEQ_ENUM_145(x) x, PDK_PP_SEQ_ENUM_144
# define PDK_PP_SEQ_ENUM_146(x) x, PDK_PP_SEQ_ENUM_145
# define PDK_PP_SEQ_ENUM_147(x) x, PDK_PP_SEQ_ENUM_146
# define PDK_PP_SEQ_ENUM_148(x) x, PDK_PP_SEQ_ENUM_147
# define PDK_PP_SEQ_ENUM_149(x) x, PDK_PP_SEQ_ENUM_148
# define PDK_PP_SEQ_ENUM_150(x) x, PDK_PP_SEQ_ENUM_149
# define PDK_PP_SEQ_ENUM_151(x) x, PDK_PP_SEQ_ENUM_150
# define PDK_PP_SEQ_ENUM_152(x) x, PDK_PP_SEQ_ENUM_151
# define PDK_PP_SEQ_ENUM_153(x) x, PDK_PP_SEQ_ENUM_152
# define PDK_PP_SEQ_ENUM_154(x) x, PDK_PP_SEQ_ENUM_153
# define PDK_PP_SEQ_ENUM_155(x) x, PDK_PP_SEQ_ENUM_154
# define PDK_PP_SEQ_ENUM_156(x) x, PDK_PP_SEQ_ENUM_155
# define PDK_PP_SEQ_ENUM_157(x) x, PDK_PP_SEQ_ENUM_156
# define PDK_PP_SEQ_ENUM_158(x) x, PDK_PP_SEQ_ENUM_157
# define PDK_PP_SEQ_ENUM_159(x) x, PDK_PP_SEQ_ENUM_158
# define PDK_PP_SEQ_ENUM_160(x) x, PDK_PP_SEQ_ENUM_159
# define PDK_PP_SEQ_ENUM_161(x) x, PDK_PP_SEQ_ENUM_160
# define PDK_PP_SEQ_ENUM_162(x) x, PDK_PP_SEQ_ENUM_161
# define PDK_PP_SEQ_ENUM_163(x) x, PDK_PP_SEQ_ENUM_162
# define PDK_PP_SEQ_ENUM_164(x) x, PDK_PP_SEQ_ENUM_163
# define PDK_PP_SEQ_ENUM_165(x) x, PDK_PP_SEQ_ENUM_164
# define PDK_PP_SEQ_ENUM_166(x) x, PDK_PP_SEQ_ENUM_165
# define PDK_PP_SEQ_ENUM_167(x) x, PDK_PP_SEQ_ENUM_166
# define PDK_PP_SEQ_ENUM_168(x) x, PDK_PP_SEQ_ENUM_167
# define PDK_PP_SEQ_ENUM_169(x) x, PDK_PP_SEQ_ENUM_168
# define PDK_PP_SEQ_ENUM_170(x) x, PDK_PP_SEQ_ENUM_169
# define PDK_PP_SEQ_ENUM_171(x) x, PDK_PP_SEQ_ENUM_170
# define PDK_PP_SEQ_ENUM_172(x) x, PDK_PP_SEQ_ENUM_171
# define PDK_PP_SEQ_ENUM_173(x) x, PDK_PP_SEQ_ENUM_172
# define PDK_PP_SEQ_ENUM_174(x) x, PDK_PP_SEQ_ENUM_173
# define PDK_PP_SEQ_ENUM_175(x) x, PDK_PP_SEQ_ENUM_174
# define PDK_PP_SEQ_ENUM_176(x) x, PDK_PP_SEQ_ENUM_175
# define PDK_PP_SEQ_ENUM_177(x) x, PDK_PP_SEQ_ENUM_176
# define PDK_PP_SEQ_ENUM_178(x) x, PDK_PP_SEQ_ENUM_177
# define PDK_PP_SEQ_ENUM_179(x) x, PDK_PP_SEQ_ENUM_178
# define PDK_PP_SEQ_ENUM_180(x) x, PDK_PP_SEQ_ENUM_179
# define PDK_PP_SEQ_ENUM_181(x) x, PDK_PP_SEQ_ENUM_180
# define PDK_PP_SEQ_ENUM_182(x) x, PDK_PP_SEQ_ENUM_181
# define PDK_PP_SEQ_ENUM_183(x) x, PDK_PP_SEQ_ENUM_182
# define PDK_PP_SEQ_ENUM_184(x) x, PDK_PP_SEQ_ENUM_183
# define PDK_PP_SEQ_ENUM_185(x) x, PDK_PP_SEQ_ENUM_184
# define PDK_PP_SEQ_ENUM_186(x) x, PDK_PP_SEQ_ENUM_185
# define PDK_PP_SEQ_ENUM_187(x) x, PDK_PP_SEQ_ENUM_186
# define PDK_PP_SEQ_ENUM_188(x) x, PDK_PP_SEQ_ENUM_187
# define PDK_PP_SEQ_ENUM_189(x) x, PDK_PP_SEQ_ENUM_188
# define PDK_PP_SEQ_ENUM_190(x) x, PDK_PP_SEQ_ENUM_189
# define PDK_PP_SEQ_ENUM_191(x) x, PDK_PP_SEQ_ENUM_190
# define PDK_PP_SEQ_ENUM_192(x) x, PDK_PP_SEQ_ENUM_191
# define PDK_PP_SEQ_ENUM_193(x) x, PDK_PP_SEQ_ENUM_192
# define PDK_PP_SEQ_ENUM_194(x) x, PDK_PP_SEQ_ENUM_193
# define PDK_PP_SEQ_ENUM_195(x) x, PDK_PP_SEQ_ENUM_194
# define PDK_PP_SEQ_ENUM_196(x) x, PDK_PP_SEQ_ENUM_195
# define PDK_PP_SEQ_ENUM_197(x) x, PDK_PP_SEQ_ENUM_196
# define PDK_PP_SEQ_ENUM_198(x) x, PDK_PP_SEQ_ENUM_197
# define PDK_PP_SEQ_ENUM_199(x) x, PDK_PP_SEQ_ENUM_198
# define PDK_PP_SEQ_ENUM_200(x) x, PDK_PP_SEQ_ENUM_199
# define PDK_PP_SEQ_ENUM_201(x) x, PDK_PP_SEQ_ENUM_200
# define PDK_PP_SEQ_ENUM_202(x) x, PDK_PP_SEQ_ENUM_201
# define PDK_PP_SEQ_ENUM_203(x) x, PDK_PP_SEQ_ENUM_202
# define PDK_PP_SEQ_ENUM_204(x) x, PDK_PP_SEQ_ENUM_203
# define PDK_PP_SEQ_ENUM_205(x) x, PDK_PP_SEQ_ENUM_204
# define PDK_PP_SEQ_ENUM_206(x) x, PDK_PP_SEQ_ENUM_205
# define PDK_PP_SEQ_ENUM_207(x) x, PDK_PP_SEQ_ENUM_206
# define PDK_PP_SEQ_ENUM_208(x) x, PDK_PP_SEQ_ENUM_207
# define PDK_PP_SEQ_ENUM_209(x) x, PDK_PP_SEQ_ENUM_208
# define PDK_PP_SEQ_ENUM_210(x) x, PDK_PP_SEQ_ENUM_209
# define PDK_PP_SEQ_ENUM_211(x) x, PDK_PP_SEQ_ENUM_210
# define PDK_PP_SEQ_ENUM_212(x) x, PDK_PP_SEQ_ENUM_211
# define PDK_PP_SEQ_ENUM_213(x) x, PDK_PP_SEQ_ENUM_212
# define PDK_PP_SEQ_ENUM_214(x) x, PDK_PP_SEQ_ENUM_213
# define PDK_PP_SEQ_ENUM_215(x) x, PDK_PP_SEQ_ENUM_214
# define PDK_PP_SEQ_ENUM_216(x) x, PDK_PP_SEQ_ENUM_215
# define PDK_PP_SEQ_ENUM_217(x) x, PDK_PP_SEQ_ENUM_216
# define PDK_PP_SEQ_ENUM_218(x) x, PDK_PP_SEQ_ENUM_217
# define PDK_PP_SEQ_ENUM_219(x) x, PDK_PP_SEQ_ENUM_218
# define PDK_PP_SEQ_ENUM_220(x) x, PDK_PP_SEQ_ENUM_219
# define PDK_PP_SEQ_ENUM_221(x) x, PDK_PP_SEQ_ENUM_220
# define PDK_PP_SEQ_ENUM_222(x) x, PDK_PP_SEQ_ENUM_221
# define PDK_PP_SEQ_ENUM_223(x) x, PDK_PP_SEQ_ENUM_222
# define PDK_PP_SEQ_ENUM_224(x) x, PDK_PP_SEQ_ENUM_223
# define PDK_PP_SEQ_ENUM_225(x) x, PDK_PP_SEQ_ENUM_224
# define PDK_PP_SEQ_ENUM_226(x) x, PDK_PP_SEQ_ENUM_225
# define PDK_PP_SEQ_ENUM_227(x) x, PDK_PP_SEQ_ENUM_226
# define PDK_PP_SEQ_ENUM_228(x) x, PDK_PP_SEQ_ENUM_227
# define PDK_PP_SEQ_ENUM_229(x) x, PDK_PP_SEQ_ENUM_228
# define PDK_PP_SEQ_ENUM_230(x) x, PDK_PP_SEQ_ENUM_229
# define PDK_PP_SEQ_ENUM_231(x) x, PDK_PP_SEQ_ENUM_230
# define PDK_PP_SEQ_ENUM_232(x) x, PDK_PP_SEQ_ENUM_231
# define PDK_PP_SEQ_ENUM_233(x) x, PDK_PP_SEQ_ENUM_232
# define PDK_PP_SEQ_ENUM_234(x) x, PDK_PP_SEQ_ENUM_233
# define PDK_PP_SEQ_ENUM_235(x) x, PDK_PP_SEQ_ENUM_234
# define PDK_PP_SEQ_ENUM_236(x) x, PDK_PP_SEQ_ENUM_235
# define PDK_PP_SEQ_ENUM_237(x) x, PDK_PP_SEQ_ENUM_236
# define PDK_PP_SEQ_ENUM_238(x) x, PDK_PP_SEQ_ENUM_237
# define PDK_PP_SEQ_ENUM_239(x) x, PDK_PP_SEQ_ENUM_238
# define PDK_PP_SEQ_ENUM_240(x) x, PDK_PP_SEQ_ENUM_239
# define PDK_PP_SEQ_ENUM_241(x) x, PDK_PP_SEQ_ENUM_240
# define PDK_PP_SEQ_ENUM_242(x) x, PDK_PP_SEQ_ENUM_241
# define PDK_PP_SEQ_ENUM_243(x) x, PDK_PP_SEQ_ENUM_242
# define PDK_PP_SEQ_ENUM_244(x) x, PDK_PP_SEQ_ENUM_243
# define PDK_PP_SEQ_ENUM_245(x) x, PDK_PP_SEQ_ENUM_244
# define PDK_PP_SEQ_ENUM_246(x) x, PDK_PP_SEQ_ENUM_245
# define PDK_PP_SEQ_ENUM_247(x) x, PDK_PP_SEQ_ENUM_246
# define PDK_PP_SEQ_ENUM_248(x) x, PDK_PP_SEQ_ENUM_247
# define PDK_PP_SEQ_ENUM_249(x) x, PDK_PP_SEQ_ENUM_248
# define PDK_PP_SEQ_ENUM_250(x) x, PDK_PP_SEQ_ENUM_249
# define PDK_PP_SEQ_ENUM_251(x) x, PDK_PP_SEQ_ENUM_250
# define PDK_PP_SEQ_ENUM_252(x) x, PDK_PP_SEQ_ENUM_251
# define PDK_PP_SEQ_ENUM_253(x) x, PDK_PP_SEQ_ENUM_252
# define PDK_PP_SEQ_ENUM_254(x) x, PDK_PP_SEQ_ENUM_253
# define PDK_PP_SEQ_ENUM_255(x) x, PDK_PP_SEQ_ENUM_254
# define PDK_PP_SEQ_ENUM_256(x) x, PDK_PP_SEQ_ENUM_255

#endif // PDK_STDEXT_PREPROCESSOR_SEQ_ENUM_H
