// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/01/18.

// ****************************************************************************
// *                                                                          *
// *     (C) Copyright Paul Mensonides 2002-2011.                             *
// *     (C) Copyright Edward Diener 2011.                                    *
// *     Distributed under the Boost Software License, Version 1.0. (See      *
// *     accompanying file LICENSE_1_0.txt or copy at                         *
// *     http://www.boost.org/LICENSE_1_0.txt)                                *
// *                                                                          *
// ****************************************************************************
// 
// See http://www.boost.org for most recent version.

#ifndef PDK_STDEXT_PREPROCESSOR_SEQ_FOREACH_PRODUCT_H
#define PDK_STDEXT_PREPROCESSOR_SEQ_FOREACH_PRODUCT_H

#include "pdk/stdext/preprocessor/arithmetic/Dec.h"
#include "pdk/stdext/preprocessor/config/Config.h"
#include "pdk/stdext/preprocessor/control/If.h"
#include "pdk/stdext/preprocessor/repetition/For.h"
#include "pdk/stdext/preprocessor/seq/Seq.h"
#include "pdk/stdext/preprocessor/seq/Size.h"
#include "pdk/stdext/preprocessor/tuple/Element.h"
#include "pdk/stdext/preprocessor/tuple/Rem.h"

// PDK_PP_SEQ_FOR_EACH_PRODUCT
# define PDK_PP_SEQ_FOR_EACH_PRODUCT(macro, sets) PDK_PP_SEQ_FOR_EACH_PRODUCT_E(PDK_PP_FOR, macro, sets)

// PDK_PP_SEQ_FOR_EACH_PRODUCT_R
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_R(r, macro, sets) PDK_PP_SEQ_FOR_EACH_PRODUCT_E(PDK_PP_FOR_ ## r, macro, sets)
#
# if ~PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_EDG()
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) impl((PDK_PP_SEQ_HEAD(sets)(nil), PDK_PP_SEQ_TAIL(sets)(nil), (nil), macro), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# else
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) PDK_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets)
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets) impl((PDK_PP_SEQ_HEAD(sets)(nil), PDK_PP_SEQ_TAIL(sets)(nil), (nil), macro), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# endif

# if PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_STRICT()
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_P_I data
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_P_I(cset, rset, res, macro) PDK_PP_DEC(PDK_PP_SEQ_SIZE(cset))
# else
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) PDK_PP_DEC(PDK_PP_SEQ_SIZE(PDK_PP_TUPLE_ELEM(4, 0, data)))
# endif

# if ~PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_MWCC()
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_O_I data
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_O_I(cset, rset, res, macro) (PDK_PP_SEQ_TAIL(cset), rset, res, macro)
# else
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) (PDK_PP_SEQ_TAIL(PDK_PP_TUPLE_ELEM(4, 0, data)), PDK_PP_TUPLE_ELEM(4, 1, data), PDK_PP_TUPLE_ELEM(4, 2, data), PDK_PP_TUPLE_ELEM(4, 3, data))
# endif

# define PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, i) PDK_PP_IF(PDK_PP_DEC(PDK_PP_SEQ_SIZE(PDK_PP_TUPLE_ELEM(4, 1, data))), PDK_PP_SEQ_FOR_EACH_PRODUCT_N_ ## i, PDK_PP_SEQ_FOR_EACH_PRODUCT_I)
#
# if ~PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_EDG()
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, PDK_PP_TUPLE_ELEM(4, 0, data), PDK_PP_TUPLE_ELEM(4, 1, data), PDK_PP_TUPLE_ELEM(4, 2, data), PDK_PP_TUPLE_ELEM(4, 3, data))
# else
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, PDK_PP_TUPLE_REM_4 data)
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, im) PDK_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, im)
# endif

# define PDK_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, cset, rset, res, macro) macro(r, PDK_PP_SEQ_TAIL(res (PDK_PP_SEQ_HEAD(cset))))
#
# if ~PDK_PP_CONFIG_FLAGS() & PDK_PP_CONFIG_MWCC()
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data) PDK_PP_SEQ_FOR_EACH_PRODUCT_H_I data
# else
#    define PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data) PDK_PP_SEQ_FOR_EACH_PRODUCT_H_I(PDK_PP_TUPLE_ELEM(4, 0, data), PDK_PP_TUPLE_ELEM(4, 1, data), PDK_PP_TUPLE_ELEM(4, 2, data), PDK_PP_TUPLE_ELEM(4, 3, data))
# endif

# define PDK_PP_SEQ_FOR_EACH_PRODUCT_H_I(cset, rset, res, macro) (PDK_PP_SEQ_HEAD(rset)(nil), PDK_PP_SEQ_TAIL(rset), res (PDK_PP_SEQ_HEAD(cset)), macro)

# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_0(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 0)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_1(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 1)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_2(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 2)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_3(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 3)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_4(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 4)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_5(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 5)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_6(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 6)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_7(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 7)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_8(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 8)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_9(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 9)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_10(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 10)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_11(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 11)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_12(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 12)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_13(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 13)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_14(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 14)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_15(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 15)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_16(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 16)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_17(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 17)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_18(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 18)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_19(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 19)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_20(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 20)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_21(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 21)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_22(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 22)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_23(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 23)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_24(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 24)(r, data)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_M_25(r, data) PDK_PP_SEQ_FOR_EACH_PRODUCT_C(data, 25)(r, data)
#
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_0(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_1)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_1(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_2)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_2(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_3)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_3(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_4)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_4(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_5)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_5(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_6)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_6(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_7)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_7(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_8)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_8(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_9)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_9(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_10)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_10(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_11)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_11(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_12)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_12(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_13)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_13(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_14)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_14(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_15)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_15(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_16)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_16(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_17)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_17(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_18)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_18(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_19)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_19(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_20)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_20(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_21)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_21(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_22)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_22(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_23)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_23(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_24)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_24(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_25)
# define PDK_PP_SEQ_FOR_EACH_PRODUCT_N_25(r, data) PDK_PP_FOR_ ## r(PDK_PP_SEQ_FOR_EACH_PRODUCT_H(data), PDK_PP_SEQ_FOR_EACH_PRODUCT_P, PDK_PP_SEQ_FOR_EACH_PRODUCT_O, PDK_PP_SEQ_FOR_EACH_PRODUCT_M_26)

#endif // PDK_STDEXT_PREPROCESSOR_SEQ_FOREACH_PRODUCT_H
