// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/01/16.

// ****************************************************************************
// *                                                                          *
// *     (C) Copyright Paul Mensonides 2002-2011.                             *
// *     (C) Copyright Edward Diener 2011.                                    *
// *     Distributed under the Boost Software License, Version 1.0. (See      *
// *     accompanying file LICENSE_1_0.txt or copy at                         *
// *     http://www.boost.org/LICENSE_1_0.txt)                                *
// *                                                                          *
// ****************************************************************************
// 
// See http://www.boost.org for most recent version.

# ifndef PDK_PP_VALUE
#    error PDK_PP_ERROR:  PDK_PP_VALUE is not defined
# endif

# undef PDK_PP_SLOT_TEMP_1
# undef PDK_PP_SLOT_TEMP_2
# undef PDK_PP_SLOT_TEMP_3
# undef PDK_PP_SLOT_TEMP_4
# undef PDK_PP_SLOT_TEMP_5
# undef PDK_PP_SLOT_TEMP_6
# undef PDK_PP_SLOT_TEMP_7
# undef PDK_PP_SLOT_TEMP_8
# undef PDK_PP_SLOT_TEMP_9
# undef PDK_PP_SLOT_TEMP_10

# if (PDK_PP_VALUE) / 1000000000UL == 0
#    define PDK_PP_SLOT_TEMP_10 0
# elif (PDK_PP_VALUE) / 1000000000UL == 1
#    define PDK_PP_SLOT_TEMP_10 1
# elif (PDK_PP_VALUE) / 1000000000UL == 2
#    define PDK_PP_SLOT_TEMP_10 2
# elif (PDK_PP_VALUE) / 1000000000UL == 3
#    define PDK_PP_SLOT_TEMP_10 3
# elif (PDK_PP_VALUE) / 1000000000UL == 4
#    define PDK_PP_SLOT_TEMP_10 4
# elif (PDK_PP_VALUE) / 1000000000UL == 5
#    define PDK_PP_SLOT_TEMP_10 5
# elif (PDK_PP_VALUE) / 1000000000UL == 6
#    define PDK_PP_SLOT_TEMP_10 6
# elif (PDK_PP_VALUE) / 1000000000UL == 7
#    define PDK_PP_SLOT_TEMP_10 7
# elif (PDK_PP_VALUE) / 1000000000UL == 8
#    define PDK_PP_SLOT_TEMP_10 8
# elif (PDK_PP_VALUE) / 1000000000UL == 9
#    define PDK_PP_SLOT_TEMP_10 9
# endif

# if PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 0
#    define PDK_PP_SLOT_TEMP_9 0
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 1
#    define PDK_PP_SLOT_TEMP_9 1
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 2
#    define PDK_PP_SLOT_TEMP_9 2
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 3
#    define PDK_PP_SLOT_TEMP_9 3
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 4
#    define PDK_PP_SLOT_TEMP_9 4
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 5
#    define PDK_PP_SLOT_TEMP_9 5
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 6
#    define PDK_PP_SLOT_TEMP_9 6
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 7
#    define PDK_PP_SLOT_TEMP_9 7
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 8
#    define PDK_PP_SLOT_TEMP_9 8
# elif PDK_PP_SLOT_OFFSET_10(PDK_PP_VALUE) / 100000000UL == 9
#    define PDK_PP_SLOT_TEMP_9 9
# endif

# if PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 0
#    define PDK_PP_SLOT_TEMP_8 0
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 1
#    define PDK_PP_SLOT_TEMP_8 1
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 2
#    define PDK_PP_SLOT_TEMP_8 2
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 3
#    define PDK_PP_SLOT_TEMP_8 3
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 4
#    define PDK_PP_SLOT_TEMP_8 4
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 5
#    define PDK_PP_SLOT_TEMP_8 5
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 6
#    define PDK_PP_SLOT_TEMP_8 6
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 7
#    define PDK_PP_SLOT_TEMP_8 7
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 8
#    define PDK_PP_SLOT_TEMP_8 8
# elif PDK_PP_SLOT_OFFSET_9(PDK_PP_VALUE) / 10000000UL == 9
#    define PDK_PP_SLOT_TEMP_8 9
# endif

# if PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 0
#    define PDK_PP_SLOT_TEMP_7 0
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 1
#    define PDK_PP_SLOT_TEMP_7 1
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 2
#    define PDK_PP_SLOT_TEMP_7 2
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 3
#    define PDK_PP_SLOT_TEMP_7 3
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 4
#    define PDK_PP_SLOT_TEMP_7 4
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 5
#    define PDK_PP_SLOT_TEMP_7 5
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 6
#    define PDK_PP_SLOT_TEMP_7 6
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 7
#    define PDK_PP_SLOT_TEMP_7 7
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 8
#    define PDK_PP_SLOT_TEMP_7 8
# elif PDK_PP_SLOT_OFFSET_8(PDK_PP_VALUE) / 1000000UL == 9
#    define PDK_PP_SLOT_TEMP_7 9
# endif

# if PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 0
#    define PDK_PP_SLOT_TEMP_6 0
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 1
#    define PDK_PP_SLOT_TEMP_6 1
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 2
#    define PDK_PP_SLOT_TEMP_6 2
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 3
#    define PDK_PP_SLOT_TEMP_6 3
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 4
#    define PDK_PP_SLOT_TEMP_6 4
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 5
#    define PDK_PP_SLOT_TEMP_6 5
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 6
#    define PDK_PP_SLOT_TEMP_6 6
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 7
#    define PDK_PP_SLOT_TEMP_6 7
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 8
#    define PDK_PP_SLOT_TEMP_6 8
# elif PDK_PP_SLOT_OFFSET_7(PDK_PP_VALUE) / 100000UL == 9
#    define PDK_PP_SLOT_TEMP_6 9
# endif

# if PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 0
#    define PDK_PP_SLOT_TEMP_5 0
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 1
#    define PDK_PP_SLOT_TEMP_5 1
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 2
#    define PDK_PP_SLOT_TEMP_5 2
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 3
#    define PDK_PP_SLOT_TEMP_5 3
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 4
#    define PDK_PP_SLOT_TEMP_5 4
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 5
#    define PDK_PP_SLOT_TEMP_5 5
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 6
#    define PDK_PP_SLOT_TEMP_5 6
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 7
#    define PDK_PP_SLOT_TEMP_5 7
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 8
#    define PDK_PP_SLOT_TEMP_5 8
# elif PDK_PP_SLOT_OFFSET_6(PDK_PP_VALUE) / 10000UL == 9
#    define PDK_PP_SLOT_TEMP_5 9
# endif

# if PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 0
#    define PDK_PP_SLOT_TEMP_4 0
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 1
#    define PDK_PP_SLOT_TEMP_4 1
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 2
#    define PDK_PP_SLOT_TEMP_4 2
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 3
#    define PDK_PP_SLOT_TEMP_4 3
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 4
#    define PDK_PP_SLOT_TEMP_4 4
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 5
#    define PDK_PP_SLOT_TEMP_4 5
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 6
#    define PDK_PP_SLOT_TEMP_4 6
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 7
#    define PDK_PP_SLOT_TEMP_4 7
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 8
#    define PDK_PP_SLOT_TEMP_4 8
# elif PDK_PP_SLOT_OFFSET_5(PDK_PP_VALUE) / 1000UL == 9
#    define PDK_PP_SLOT_TEMP_4 9
# endif

# if PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 0
#    define PDK_PP_SLOT_TEMP_3 0
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 1
#    define PDK_PP_SLOT_TEMP_3 1
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 2
#    define PDK_PP_SLOT_TEMP_3 2
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 3
#    define PDK_PP_SLOT_TEMP_3 3
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 4
#    define PDK_PP_SLOT_TEMP_3 4
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 5
#    define PDK_PP_SLOT_TEMP_3 5
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 6
#    define PDK_PP_SLOT_TEMP_3 6
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 7
#    define PDK_PP_SLOT_TEMP_3 7
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 8
#    define PDK_PP_SLOT_TEMP_3 8
# elif PDK_PP_SLOT_OFFSET_4(PDK_PP_VALUE) / 100UL == 9
#    define PDK_PP_SLOT_TEMP_3 9
# endif

# if PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 0
#    define PDK_PP_SLOT_TEMP_2 0
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 1
#    define PDK_PP_SLOT_TEMP_2 1
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 2
#    define PDK_PP_SLOT_TEMP_2 2
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 3
#    define PDK_PP_SLOT_TEMP_2 3
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 4
#    define PDK_PP_SLOT_TEMP_2 4
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 5
#    define PDK_PP_SLOT_TEMP_2 5
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 6
#    define PDK_PP_SLOT_TEMP_2 6
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 7
#    define PDK_PP_SLOT_TEMP_2 7
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 8
#    define PDK_PP_SLOT_TEMP_2 8
# elif PDK_PP_SLOT_OFFSET_3(PDK_PP_VALUE) / 10UL == 9
#    define PDK_PP_SLOT_TEMP_2 9
# endif

# if PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 0
#    define PDK_PP_SLOT_TEMP_1 0
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 1
#    define PDK_PP_SLOT_TEMP_1 1
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 2
#    define PDK_PP_SLOT_TEMP_1 2
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 3
#    define PDK_PP_SLOT_TEMP_1 3
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 4
#    define PDK_PP_SLOT_TEMP_1 4
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 5
#    define PDK_PP_SLOT_TEMP_1 5
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 6
#    define PDK_PP_SLOT_TEMP_1 6
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 7
#    define PDK_PP_SLOT_TEMP_1 7
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 8
#    define PDK_PP_SLOT_TEMP_1 8
# elif PDK_PP_SLOT_OFFSET_2(PDK_PP_VALUE) == 9
#    define PDK_PP_SLOT_TEMP_1 9
# endif

# undef PDK_PP_VALUE

