// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/01/25.

#ifndef PDK_KERNEL_INTERNAL_DEADLINE_TIMER_PRIVATE_H
#define PDK_KERNEL_INTERNAL_DEADLINE_TIMER_PRIVATE_H

namespace pdk {
namespace kernel {
namespace internal {

enum {
#if defined(PDK_OS_UNIX) && !defined(PDK_OS_DARWIN)
    // t1 contains seconds and t2 contains nanoseconds
    DeadlineTimerNanosecondsInT2 = 1
#else
    // t1 contains nanoseconds, t2 is always zero
    DeadlineTimerNanosecondsInT2 = 0
#endif
};

} // internal
} // kernel
} // pdk

#endif // PDK_KERNEL_INTERNAL_DEADLINE_TIMER_PRIVATE_H
