// @copyright 2017-2018 zzu_softboy <zzu_softboy@163.com>
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Created by softboy on 2018/03/26.

#ifndef PDK_TESTLIB_GLOBAL_H
#define PDK_TESTLIB_GLOBAL_H

#include "pdk/global/Global.h"

#if defined(PDK_STATIC)
# define PDK_TESTLIB_EXPORT
#else
# ifdef PDK_BUILD_TESTLIB_LIB
#  define PDK_TESTLIB_EXPORT PDK_DECL_EXPORT
# else
#  define PDK_TESTLIB_EXPORT PDK_DECL_IMPORT
# endif
#endif

#if (defined PDK_CC_HPACC) && (defined __ia64)
# ifdef PDK_TESTLIB_EXPORT
#  undef PDK_TESTLIB_EXPORT
# endif
# define PDK_TESTLIB_EXPORT
#endif

namespace pdktest {

}

#endif // PDK_TESTLIB_GLOBAL_H
